### ISSUE TITLE
File Links Are Incorrect

### ISSUE THREAD

**Issue by ghost** [eternalxlks/eternalxlks.github.io#4]
These two file links below are part of your local file system and will not work on anyone else's computer.

- file:///home/chronos/u-7ce57aaa5ff512f11b03bd3e13f962af77a938b6/MyFiles/Pong/Pong.html [\[Line 22\]](https://github.com/eternalxlks/eternalxlks.github.io/blob/e2064342101e49380788af14978799073ebd3de3/index.html#L22)
- file:///home/chronos/u-7ce57aaa5ff512f11b03bd3e13f962af77a938b6/MyFiles/Pong/PongCode.txt [\[Line 24\]](https://github.com/eternalxlks/eternalxlks.github.io/blob/e2064342101e49380788af14978799073ebd3de3/index.html#L24)

You can tell it is part of your file system because it starts with "file://", and not "http://" or "https://".

This problem is easily fixable by uploading these files onto GitHub. If you need help, check out this documentation page about [uploading a file to GitHub.](https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository)

**Comment by infinitexlks** [comment]
NOPE!

**Comment by ghost** [comment]
Did you forget to close the issue?
